// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: role/role.proto

package role

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ListReqMultiError, or nil if none found.
func (m *ListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListReqMultiError(errors)
	}

	return nil
}

// ListReqMultiError is an error wrapping multiple validation errors returned
// by ListReq.ValidateAll() if the designated constraints aren't met.
type ListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReqMultiError) AllErrors() []error { return m }

// ListReqValidationError is the validation error returned by ListReq.Validate
// if the designated constraints aren't met.
type ListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReqValidationError) ErrorName() string { return "ListReqValidationError" }

// Error satisfies the builtin error interface
func (e ListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReqValidationError{}

// Validate checks the field values on ListRes with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListRes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRes with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ListResMultiError, or nil if none found.
func (m *ListRes) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListResMultiError(errors)
	}

	return nil
}

// ListResMultiError is an error wrapping multiple validation errors returned
// by ListRes.ValidateAll() if the designated constraints aren't met.
type ListResMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListResMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListResMultiError) AllErrors() []error { return m }

// ListResValidationError is the validation error returned by ListRes.Validate
// if the designated constraints aren't met.
type ListResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListResValidationError) ErrorName() string { return "ListResValidationError" }

// Error satisfies the builtin error interface
func (e ListResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListResValidationError{}
